[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://ark-ii.netlify.app/*"
  to = "https://ark-ii.studio/:splat"
  status = 301
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
